version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend/src:/app/src
    environment:
      - NODE_ENV=development
      - PORT=5000

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
    environment:
      - NODE_ENV=development
      - VITE_API_URL=http://backend:5000
    depends_on:
      - backend

networks:
  default:
    driver: bridge